# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiry_month',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='p_short',
            field=models.CharField(default='helo', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='expiry',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
