# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_auto_20170219_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plist',
            fields=[
                ('tfield', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purch_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateField()),
                ('remarks', models.CharField(max_length=200)),
                ('response', models.CharField(max_length=200)),
                ('responded', models.IntegerField(default=0)),
                ('total', models.FloatField()),
                ('adm_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.User')),
            ],
        ),
        migrations.AddField(
            model_name='plist',
            name='purch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.Purchase'),
        ),
    ]
