# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_auto_20170219_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isadmin',
            field=models.IntegerField(default=0),
        ),
    ]
